dummy.cache.duration.hours=time cache durration
dummy.load.cache.cron=cron for reload settings cache
setting.mock.file.dirs.path=Paths to mock settings dirs may be list with separator like ','
server.http.port=server http port
server.port=server https port
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=passwd
server.ssl.key-store-type=PKCS12