dummy.cache.duration.hours=24
dummy.load.cache.cron=*/30 * * * * *
setting.mock.file.dirs.path=./config/mocks_conf/
logging.level.root=info
logging.level.org.springframework.web=info
server.http.port=8982
server.port=8983
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=passwd
server.ssl.key-store-type=PKCS12